accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
      #dashboard page or homepage
    path('',views.dashboard,name='dashboard'),

    #login and logout path
    path('login/',auth_views.LoginView.as_view(),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),

    #register 

    path('register/',views.register,name='register'),
    
    #edit
    path('edit/',views.edit,name='edit'),

    path('users/',views.user_list,name='user_list'),
    path('dashboard/',views.dashboard,name='dashboard'),
   
    path('users/follow/',views.user_follow,name='user_follow'),
    path('users/<username>',views.user_detail,name='user_detail'),


  
]

images/urls.py
from django.urls import path
from . import views


app_name='images'
urlpatterns=[
    #image create view
    path('create/',views.image_create,name='create'),
    #image detail view
    path('detail/<int:id>/<slug:slug>/',views.image_detail,name='detail'),

    #like
    path('like/',views.image_like,name='like'),
    #homepage
    path('',views.image_list,name='list'),

    
]

shareshot/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from django.views.static import serve
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('accounts.urls')),
    path('images/',include('images.urls',namespace='image')),

    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User

class Profile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    date_of_birth=models.DateField(blank=True,null=True)
    photo=models.ImageField(upload_to='users/%y/%m/%d/',blank=True)

class Contact(models.Model):
    user_from=models.ForeignKey('auth.User',related_name='rel_from_set',on_delete=models.CASCADE)   
    user_to= models.ForeignKey('auth.User',related_name='rel_to_set',on_delete=models.CASCADE)   
    created=models.DateTimeField(auto_now_add=True,db_index=True)
    class Meta:
        ordering=('created',)

    def __str__(self):
        return '{} follows {}'.format(self.user_from,self.user_to)   
        
#ADD THE FOLLOWING FIELD TO USER DYNAMICALLY
User.add_to_class('following',models.ManyToManyField('self',through=Contact,related_name='followers',symmetrical=False))

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class UserRegistrationForm(forms.ModelForm):
    password=forms.CharField(label='password',widget=forms.PasswordInput)
    password2=forms.CharField(label='Repeat password',widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ("username","first_name","email")
    def clean_password2(self):
        cd=self.cleaned_data
        if cd['password']!=cd['password2']:
            raise forms.ValidationError('password didnot match')
        return cd['password']   

class UserEditForm(forms.ModelForm):
    class Meta:
        model=User
        fields=('first_name','email','last_name')

class ProfileEditForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('date_of_birth','photo')

accounts/views.py
import json
from django.shortcuts import render

from django.contrib.auth.decorators import login_required
from .forms import UserRegistrationForm,UserEditForm,ProfileEditForm
from .models import Profile

from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from common.decorators import ajax_required
from .models import Contact

@login_required
def dashboard(request):
    context={'section':dashboard}
    return render(request,'account/dashboard.html',context)
def register(request):
    if request.method=='POST':
        user_form=UserRegistrationForm(request.POST)
        if user_form.is_valid():
            #create a new user object but avoid saving it
            new_user=user_form.save(commit=False)
            #set the chosen password
            new_user.set_password(user_form.cleaned_data['password'])
            #save the object
            new_user.save()
            #create the user profile
            Profile.objects.create(user=new_user)

            context={'new_user':new_user}
            return render(request,'account/register_done.html',context)
    else:
        user_form=UserRegistrationForm()
    context={'user_form':user_form}    
    return render(request,'account/register.html',context)       

@login_required
def edit(request):
    if request.method=='POST':
        user_form=UserEditForm(instance=request.user,data=request.POST)
        profile_form=ProfileEditForm(instance=request.user.profile,data=request.POST,files=request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form=UserEditForm(instance=request.user)  
        profile_form=ProfileEditForm(instance=request.user.profile)  

    context={'user_form':user_form,'profile_form':profile_form}
    return render(request,'account/edit.html',context)      


@login_required
def user_list(request):
    users=User.objects.filter(is_active=True)
    context={'section':'people','users':users}
    return render(request,'account/user/list.html',context)   

def user_detail(request,username):
    user=get_object_or_404(User,username=username,is_active=True)
    context={'section':'people','user':user}
    return render(request,'account/user/detail.html',context)       


@login_required
def dashboard(request):
    users=User.objects.filter(is_active=True)
    context={'section':'dashboard','users':users}
    return render(request,'account/dashboard.html',context) 


 
    

@ajax_required
@require_POST
@login_required
def user_follow(request):
    user_id=request.POST.get('id')
    action=request.POST.get('action')
    if user_id and action:
        try:
            user=User.objects.get(id=user_id)
            if action=='follow':
                Contact.objects.get_or_create(user_from=request.user,user_to=user)
            else:
                Contact.objects.filter(user_from=request.user,user_to=user).delete()
            return JsonResponse({'status':'ok'})
        except User.DoesNotExist:
            return JsonResponse({'status':'ko'})
    return JsonResponse({'status':'ko'})

accounts/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Homepage</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="#">
    </head>
    <body>
       
        <nav class="navbar navbar-expand-lg navbar-info bg-dark">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'dashboard' %}">Shareshot</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" href="{% url 'dashboard' %}">Dashboard</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'images:list' %}">Images</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'user_list' %}">People</a>
                  </li>
                 
                  
                </ul>
                <form class="d-flex">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                          <a class="nav-link" href="#">
                        Hey {{ request.user.username }}
                        </a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'edit' %}">Edit</a>
                        
                      </li>
                     
                          
                        </li>

                      {% else %}
                        <a class="nav-link" href="{% url 'register' %}">Signup</a>
                        <a class="nav-link" href="{% url 'login' %}">Log-in</a>
                     
                      {% endif %}
                      
                 </ul>
                </form>
              </div>
            </div>
          </nav>
          <div class="content container">

          {% block content %}
              
          {% endblock  %}

        </div>

       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
       <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>

          <script>
            var csrftoken=Cookies.get('csrftoken');
            function csrfSafeMethod(method){
              //these http methods do not require csrf projection
              return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
            }
            $.ajaxSetup({
              beforeSend: function(xhr,settings){
                if (!csrfSafeMethod(settings.type)&& !this.crossDomain){
                  xhr.setRequestHeader('X-CSRFToken',csrftoken);
                }
              
              }
            });
            $(document).ready(function(){
              {% block domready %}
              {% endblock %}
            }
            );
          </script>
  

    </body>
</html>